apiVersion: apps/v1
kind: Deployment
metadata:
  name: facilitator
  labels:
    topology.kubernetes.io/region: ap-southeast-1
spec:
  template:
    metadata:
      labels:
        topology.kubernetes.io/region: ap-southeast-1
    spec:
      nodeSelector:
        topology.kubernetes.io/region: ap-southeast-1
      tolerations:
        - key: "node.kubernetes.io/region"
          operator: "Equal"
          value: "ap-southeast-1"
          effect: "NoSchedule"
