apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facilitator
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - staging-facilitator.t402.io
      secretName: staging-facilitator-tls
  rules:
    - host: staging-facilitator.t402.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-facilitator
                port:
                  name: http
