"""T402 Protocol Extensions."""

from t402.extensions.payment_id import (
    PaymentIdExtensionInfo,
    PaymentIdExtension,
    PaymentIdPayload,
    declare_payment_id_extension,
    parse_payment_id_payload,
    validate_payment_id,
)
from t402.extensions.siwx import (
    SIWxExtensionInfo,
    SIWxExtension,
    SIWxPayload,
    declare_siwx_extension,
    parse_siwx_payload,
    validate_siwx_message,
)
from t402.extensions.offer_receipt import (
    EXTENSION_KEY as OFFER_RECEIPT_KEY,
    OfferPayload,
    ReceiptPayload,
    SignedOffer,
    SignedReceipt,
    create_signed_offer,
    create_signed_receipt,
    verify_offer,
    verify_receipt,
    match_offer_to_requirements,
    is_offer_expired,
    create_offers_from_requirements,
    create_receipt_for_payment,
    extract_offers,
    extract_receipt,
)
from t402.extensions.erc8004 import (
    ERC8004Extension,
    ERC8004PayloadExtension,
    ERC8004_EXTENSION_KEY,
    declare_erc8004_extension,
    get_erc8004_extension,
    create_erc8004_payload_extension,
    verify_agent_identity,
    parse_agent_registry,
)

__all__ = [
    "PaymentIdExtensionInfo",
    "PaymentIdExtension",
    "PaymentIdPayload",
    "declare_payment_id_extension",
    "parse_payment_id_payload",
    "validate_payment_id",
    "SIWxExtensionInfo",
    "SIWxExtension",
    "SIWxPayload",
    "declare_siwx_extension",
    "parse_siwx_payload",
    "validate_siwx_message",
    "ERC8004Extension",
    "ERC8004PayloadExtension",
    "ERC8004_EXTENSION_KEY",
    "declare_erc8004_extension",
    "get_erc8004_extension",
    "create_erc8004_payload_extension",
    "verify_agent_identity",
    "parse_agent_registry",
    "OFFER_RECEIPT_KEY",
    "OfferPayload",
    "ReceiptPayload",
    "SignedOffer",
    "SignedReceipt",
    "create_signed_offer",
    "create_signed_receipt",
    "verify_offer",
    "verify_receipt",
    "match_offer_to_requirements",
    "is_offer_expired",
    "create_offers_from_requirements",
    "create_receipt_for_payment",
    "extract_offers",
    "extract_receipt",
]
