"""A2A (Agent-to-Agent) transport for t402 payments."""

from t402.a2a.types import (
    T402_A2A_EXTENSION_URI,
    X402_A2A_EXTENSION_URI,
    A2A_EXTENSIONS_HEADER,
    META_PAYMENT_STATUS,
    META_PAYMENT_REQUIRED,
    META_PAYMENT_PAYLOAD,
    META_PAYMENT_RECEIPTS,
    META_PAYMENT_ERROR,
    X402_META_PAYMENT_STATUS,
    X402_META_PAYMENT_REQUIRED,
    X402_META_PAYMENT_PAYLOAD,
    X402_META_PAYMENT_RECEIPTS,
    X402_META_PAYMENT_ERROR,
    CAIP2_TO_FLAT_NAME,
    T402_TO_X402_ERROR_MAP,
    STATUS_PAYMENT_REQUIRED,
    STATUS_PAYMENT_REJECTED,
    STATUS_PAYMENT_SUBMITTED,
    STATUS_PAYMENT_VERIFIED,
    STATUS_PAYMENT_COMPLETED,
    STATUS_PAYMENT_FAILED,
    A2AMessagePart,
    A2AMessage,
    A2ATaskStatus,
    A2AArtifact,
    A2ATask,
    A2AExtension,
    A2AAgentCard,
    A2ASkill,
)
from t402.a2a.helpers import (
    is_payment_required,
    is_payment_completed,
    is_payment_failed,
    get_payment_required,
    get_payment_receipts,
    has_payment_payload,
    extract_payment_payload,
    map_t402_error_to_x402,
    downgrade_requirements_to_x402,
    is_standalone_flow,
    is_embedded_flow,
    create_payment_required_message,
    create_payment_submission_message,
    create_payment_completed_message,
    create_payment_failed_message,
    create_t402_extension,
    create_x402_extension,
)
from t402.a2a.ap2 import (
    # Constants
    AP2_EXTENSION_URI,
    X402_PAYMENT_METHOD,
    AP2_DATA_KEY_INTENT_MANDATE,
    AP2_DATA_KEY_CART_MANDATE,
    AP2_DATA_KEY_PAYMENT_MANDATE,
    AP2_DATA_KEY_PAYMENT_RECEIPT,
    # Types
    PaymentCurrencyAmount,
    PaymentItem,
    AP2PaymentMethodData,
    AP2PaymentDetailsInit,
    AP2PaymentRequest,
    AP2PaymentResponse,
    IntentMandate,
    CartContents,
    CartMandate,
    PaymentMandateContents,
    PaymentMandate,
    AP2PaymentReceipt,
    # Bridge functions
    create_cart_mandate_with_x402,
    extract_x402_requirements,
    create_payment_mandate_with_x402,
    extract_x402_payload,
    create_ap2_extension,
    # DataPart helpers
    create_cart_mandate_data_part,
    create_payment_mandate_data_part,
    create_intent_mandate_data_part,
    create_payment_receipt_data_part,
    extract_cart_mandate_from_artifact,
    extract_payment_mandate_from_message,
    # Phase 3 AgentCard extension composition & header helpers
    create_payment_extensions,
    get_payment_extension_headers,
)

__all__ = [
    # Phase 1 types constants
    "T402_A2A_EXTENSION_URI",
    "X402_A2A_EXTENSION_URI",
    "A2A_EXTENSIONS_HEADER",
    "META_PAYMENT_STATUS",
    "META_PAYMENT_REQUIRED",
    "META_PAYMENT_PAYLOAD",
    "META_PAYMENT_RECEIPTS",
    "META_PAYMENT_ERROR",
    "X402_META_PAYMENT_STATUS",
    "X402_META_PAYMENT_REQUIRED",
    "X402_META_PAYMENT_PAYLOAD",
    "X402_META_PAYMENT_RECEIPTS",
    "X402_META_PAYMENT_ERROR",
    "CAIP2_TO_FLAT_NAME",
    "T402_TO_X402_ERROR_MAP",
    "STATUS_PAYMENT_REQUIRED",
    "STATUS_PAYMENT_REJECTED",
    "STATUS_PAYMENT_SUBMITTED",
    "STATUS_PAYMENT_VERIFIED",
    "STATUS_PAYMENT_COMPLETED",
    "STATUS_PAYMENT_FAILED",
    "A2AMessagePart",
    "A2AMessage",
    "A2ATaskStatus",
    "A2AArtifact",
    "A2ATask",
    "A2AExtension",
    "A2AAgentCard",
    "A2ASkill",
    # Phase 1 helpers
    "is_payment_required",
    "is_payment_completed",
    "is_payment_failed",
    "get_payment_required",
    "get_payment_receipts",
    "has_payment_payload",
    "extract_payment_payload",
    "map_t402_error_to_x402",
    "downgrade_requirements_to_x402",
    "is_standalone_flow",
    "is_embedded_flow",
    "create_payment_required_message",
    "create_payment_submission_message",
    "create_payment_completed_message",
    "create_payment_failed_message",
    "create_t402_extension",
    "create_x402_extension",
    # Phase 2 AP2 constants
    "AP2_EXTENSION_URI",
    "X402_PAYMENT_METHOD",
    "AP2_DATA_KEY_INTENT_MANDATE",
    "AP2_DATA_KEY_CART_MANDATE",
    "AP2_DATA_KEY_PAYMENT_MANDATE",
    "AP2_DATA_KEY_PAYMENT_RECEIPT",
    # Phase 2 AP2 types
    "PaymentCurrencyAmount",
    "PaymentItem",
    "AP2PaymentMethodData",
    "AP2PaymentDetailsInit",
    "AP2PaymentRequest",
    "AP2PaymentResponse",
    "IntentMandate",
    "CartContents",
    "CartMandate",
    "PaymentMandateContents",
    "PaymentMandate",
    "AP2PaymentReceipt",
    # Phase 2 AP2 bridge functions
    "create_cart_mandate_with_x402",
    "extract_x402_requirements",
    "create_payment_mandate_with_x402",
    "extract_x402_payload",
    "create_ap2_extension",
    # Phase 2 AP2 DataPart helpers
    "create_cart_mandate_data_part",
    "create_payment_mandate_data_part",
    "create_intent_mandate_data_part",
    "create_payment_receipt_data_part",
    "extract_cart_mandate_from_artifact",
    "extract_payment_mandate_from_message",
    # Phase 3 AgentCard extension composition & header helpers
    "create_payment_extensions",
    "get_payment_extension_headers",
]
